/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registration.system;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.toedter.calendar.JDateChooser;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nigel
 */
public class PeopleGUI extends javax.swing.JFrame {
    private String userID;
    private final String dataUser = "dataUser.txt";
    /**
     * Creates new form People
     */
    public PeopleGUI() {
        initComponents();
    }
    
    public PeopleGUI(String userID) {
        this.userID = userID;
        initComponents();
        showProfileDetails();
        updateDashboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        genderButtonGroup = new javax.swing.ButtonGroup();
        sideMenuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        appointmentPanelButton = new javax.swing.JPanel();
        appointmentButtonLabel = new javax.swing.JLabel();
        profilePanelButton = new javax.swing.JPanel();
        profileButtonLabel = new javax.swing.JLabel();
        homePanelButton = new javax.swing.JPanel();
        homeButtonLabel = new javax.swing.JLabel();
        statusPanelButton = new javax.swing.JPanel();
        statusButtonLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mainPanels = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        virusImage = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        appointmentPanel = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ucDateText = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        ucTimeText = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        ucLocationText = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        ucVaccineText = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        apHourSlider = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        apMinuteSlider = new javax.swing.JSpinner();
        jLabel33 = new javax.swing.JLabel();
        centreCombo = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        vaccineCombo = new javax.swing.JComboBox<>();
        regButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        apDateChooser = new com.toedter.calendar.JDateChooser();
        statusPanel = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel46 = new javax.swing.JLabel();
        centreSearchCombo = new javax.swing.JComboBox<>();
        vaccineSearchCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusTable = new javax.swing.JTable();
        jLabel47 = new javax.swing.JLabel();
        searchStatusButton = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        statusDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        logOutButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        changePassPanel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        currentPassText = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        newPassText = new javax.swing.JTextField();
        cancelChangeButton = new javax.swing.JButton();
        confChangeButton = new javax.swing.JButton();
        changeProfilePanel = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        phoneNumText = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        citizenshipText = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        saveProfileButton = new javax.swing.JButton();
        changePassButton = new javax.swing.JButton();
        dobDateChooser = new com.toedter.calendar.JDateChooser();
        stateComboBox = new javax.swing.JComboBox<>();
        femaleRadioButton = new javax.swing.JRadioButton();
        maleRadioButton = new javax.swing.JRadioButton();
        jLabel44 = new javax.swing.JLabel();
        userIDText = new javax.swing.JTextField();

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Dashboard");
        setResizable(false);

        sideMenuPanel.setBackground(new java.awt.Color(41, 48, 57));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        appointmentPanelButton.setBackground(new java.awt.Color(41, 48, 57));
        appointmentPanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentPanelButtonMouseClicked(evt);
            }
        });

        appointmentButtonLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        appointmentButtonLabel.setForeground(new java.awt.Color(255, 255, 255));
        appointmentButtonLabel.setText("Appointment Booking");

        javax.swing.GroupLayout appointmentPanelButtonLayout = new javax.swing.GroupLayout(appointmentPanelButton);
        appointmentPanelButton.setLayout(appointmentPanelButtonLayout);
        appointmentPanelButtonLayout.setHorizontalGroup(
            appointmentPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentPanelButtonLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(appointmentButtonLabel)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        appointmentPanelButtonLayout.setVerticalGroup(
            appointmentPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appointmentButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        profilePanelButton.setBackground(new java.awt.Color(41, 48, 57));
        profilePanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilePanelButtonMouseClicked(evt);
            }
        });

        profileButtonLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        profileButtonLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileButtonLabel.setText("Profile");

        javax.swing.GroupLayout profilePanelButtonLayout = new javax.swing.GroupLayout(profilePanelButton);
        profilePanelButton.setLayout(profilePanelButtonLayout);
        profilePanelButtonLayout.setHorizontalGroup(
            profilePanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(profileButtonLabel)
                .addGap(103, 103, 103))
        );
        profilePanelButtonLayout.setVerticalGroup(
            profilePanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profileButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        homePanelButton.setBackground(new java.awt.Color(255, 255, 255));
        homePanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePanelButtonMouseClicked(evt);
            }
        });

        homeButtonLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        homeButtonLabel.setText("Home");

        javax.swing.GroupLayout homePanelButtonLayout = new javax.swing.GroupLayout(homePanelButton);
        homePanelButton.setLayout(homePanelButtonLayout);
        homePanelButtonLayout.setHorizontalGroup(
            homePanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelButtonLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(homeButtonLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homePanelButtonLayout.setVerticalGroup(
            homePanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        statusPanelButton.setBackground(new java.awt.Color(41, 48, 57));
        statusPanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusPanelButtonMouseClicked(evt);
            }
        });

        statusButtonLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        statusButtonLabel.setForeground(new java.awt.Color(255, 255, 255));
        statusButtonLabel.setText("View Status");

        javax.swing.GroupLayout statusPanelButtonLayout = new javax.swing.GroupLayout(statusPanelButton);
        statusPanelButton.setLayout(statusPanelButtonLayout);
        statusPanelButtonLayout.setHorizontalGroup(
            statusPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statusButtonLabel)
                .addGap(73, 73, 73))
        );
        statusPanelButtonLayout.setVerticalGroup(
            statusPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sideMenuPanelLayout = new javax.swing.GroupLayout(sideMenuPanel);
        sideMenuPanel.setLayout(sideMenuPanelLayout);
        sideMenuPanelLayout.setHorizontalGroup(
            sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sideMenuPanelLayout.createSequentialGroup()
                .addGroup(sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(homePanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(appointmentPanelButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusPanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profilePanelButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sideMenuPanelLayout.setVerticalGroup(
            sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(homePanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appointmentPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profilePanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanels.setLayout(new java.awt.CardLayout());

        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N
        homePanel.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 580, 410));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setText("Dashboard");
        homePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 6, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Your account overview");
        homePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 60, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Welcome, Powell");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLabel3.setText("You have 1 upcoming vaccination appointment");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Your Vaccination Status");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Dose 1");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel39.setText("Date:");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel40.setText("Vaccine Name:");

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel42.setText("Location:");
        jLabel42.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel6))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel39)
                            .addComponent(jLabel42))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addComponent(jLabel39)
                .addGap(55, 55, 55)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addGap(56, 56, 56))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setText("Dose 2");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel41.setText("Date:");

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel43.setText("Vaccine Name:");

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel49.setText("Location:");
        jLabel49.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel18))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel41)
                            .addComponent(jLabel49))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(31, 31, 31)
                .addComponent(jLabel41)
                .addGap(55, 55, 55)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel49)
                .addGap(56, 56, 56))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jLabel50.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel50.setText("jLabel50");
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));
        jPanel3.add(virusImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 300, 300));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        homePanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 740, 460));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N
        homePanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 110, 580, 410));

        mainPanels.add(homePanel, "homePane");

        appointmentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N
        appointmentPanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 580, 410));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("Appointment Booking");
        appointmentPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 6, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("Covid-19 Vaccine Registration Form");
        appointmentPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 60, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel31.setText("Date");
        appointmentPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel16.setText("Your Upcoming Appointment");

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_cancel_26px.png"))); // NOI18N
        cancelButton.setText("Cancel Appointment");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Date");

        ucDateText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ucDateText.setEnabled(false);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel36.setText("Time");

        ucTimeText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ucTimeText.setEnabled(false);

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel37.setText("Location");

        ucLocationText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ucLocationText.setEnabled(false);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel38.setText("Vaccine Type");

        ucVaccineText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ucVaccineText.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addGap(217, 217, 217))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ucDateText)
                    .addComponent(ucTimeText)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel37)
                        .addGap(186, 186, 186))
                    .addComponent(ucLocationText)
                    .addComponent(ucVaccineText)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel38)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(cancelButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ucDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addGap(4, 4, 4)
                .addComponent(ucTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel37)
                .addGap(3, 3, 3)
                .addComponent(ucLocationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ucVaccineText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        appointmentPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 260, 440));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel32.setText("Time");
        appointmentPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        apHourSlider.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        apHourSlider.setModel(new javax.swing.SpinnerNumberModel(1, 1, 24, 1));
        appointmentPanel.add(apHourSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 285, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setText(":");
        appointmentPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 286, -1, -1));

        apMinuteSlider.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        apMinuteSlider.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 30));
        appointmentPanel.add(apMinuteSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 285, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel33.setText("Vaccination Centre");
        appointmentPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        centreCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        centreCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "World Trade Centre KL", "Wisma Belia", "Stadium Tun Abdul Razak", "Pusat Sains dan Kreativiti", "Kuala Lumpur Convention Centre", "Ideal Convention Centre", "Borneo Convention Centre Kuching", "Axiata Arena Bukit Jalil" }));
        centreCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centreComboActionPerformed(evt);
            }
        });
        appointmentPanel.add(centreCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 357, 143, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel34.setText("Vaccine Name");
        appointmentPanel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        vaccineCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaccineCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        appointmentPanel.add(vaccineCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 429, 144, -1));

        regButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        regButton.setText("Register");
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });
        appointmentPanel.add(regButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 285, 97, -1));

        clearButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        appointmentPanel.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 357, 97, -1));

        apDateChooser.setDateFormatString("dd-MM-yyyy");
        apDateChooser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        appointmentPanel.add(apDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 143, -1));

        mainPanels.add(appointmentPanel, "appointmentPane");

        statusPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N
        statusPanel.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 580, 410));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setText("Status");
        statusPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 6, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setText("View Details of Vaccination Centres and Vaccines");
        statusPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 60, -1, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel45.setText("Search via Vaccine Type");

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel46.setText("Search via Vaccination Centre");

        centreSearchCombo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        centreSearchCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "World Trade Centre KL", "Wisma Belia", "Stadium Tun Abdul Razak", "Pusat Sains dan Kreativiti", "Kuala Lumpur Convention Centre", "Ideal Convention Centre", "Borneo Convention Centre Kuching", "Axiata Arena Bukit Jalil" }));

        vaccineSearchCombo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        vaccineSearchCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Pfizer-BioNtech", "AstraZeneca", "Janssen/Ad26.COV 2.S", "Sputnik V", "Sinovac-CoronaVac", "Cansino Biologics" }));

        statusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Centre Name", "Centre Location", "Vaccine Name", "Vaccine Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(statusTable);

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel47.setText("Vaccination Status on ");

        searchStatusButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        searchStatusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_search_26px_2.png"))); // NOI18N
        searchStatusButton.setText("Search");
        searchStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStatusButtonActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel48.setText("Date");

        statusDateChooser.setDateFormatString("dd-MM-yyyy");
        statusDateChooser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(vaccineSearchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(centreSearchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel46))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(statusDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addGap(109, 109, 109))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel47)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addComponent(searchStatusButton)
                .addGap(321, 321, 321))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel48)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(statusDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel45)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(vaccineSearchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(centreSearchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        statusPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 470));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N
        statusPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 580, 410));

        mainPanels.add(statusPanel, "statusPane");

        logOutButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_Logout_26px.png"))); // NOI18N
        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setText("Your Profile");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel14.setText("Manage Your Profile");

        changePassPanel.setPreferredSize(new java.awt.Dimension(484, 402));
        changePassPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N
        changePassPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 580, 410));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Current Password");
        changePassPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 117, 28));

        currentPassText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changePassPanel.add(currentPassText, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 184, 35));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("New Password");
        changePassPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 117, 28));

        newPassText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changePassPanel.add(newPassText, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 184, 35));

        cancelChangeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelChangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_cancel_26px.png"))); // NOI18N
        cancelChangeButton.setText("Cancel");
        cancelChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelChangeButtonActionPerformed(evt);
            }
        });
        changePassPanel.add(cancelChangeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 114, 37));

        confChangeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confChangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_confirm_26px.png"))); // NOI18N
        confChangeButton.setText("Confirm");
        confChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confChangeButtonActionPerformed(evt);
            }
        });
        changePassPanel.add(confChangeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 114, 37));

        changeProfilePanel.setRequestFocusEnabled(false);
        changeProfilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N
        changeProfilePanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 580, 410));

        phoneNumText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        changeProfilePanel.add(phoneNumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 162, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel20.setText("Phone Number");
        changeProfilePanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 130, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel19.setText("Full Name as per IC / Passport");
        changeProfilePanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 210, 20));

        nameText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        changeProfilePanel.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 162, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel23.setText("Date of Birth");
        changeProfilePanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 130, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel24.setText("State");
        changeProfilePanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 50, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel26.setText("Gender");
        changeProfilePanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 50, -1));

        citizenshipText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        changeProfilePanel.add(citizenshipText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 162, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel25.setText("Citizenship");
        changeProfilePanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 90, -1));

        saveProfileButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveProfileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_save_26px.png"))); // NOI18N
        saveProfileButton.setText("Save");
        saveProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProfileButtonActionPerformed(evt);
            }
        });
        changeProfilePanel.add(saveProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 118, 39));

        changePassButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changePassButton.setText("Change Password");
        changePassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassButtonActionPerformed(evt);
            }
        });
        changeProfilePanel.add(changePassButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 153, 39));

        dobDateChooser.setDateFormatString("dd-MM-yyyy");
        dobDateChooser.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        changeProfilePanel.add(dobDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 162, -1));

        stateComboBox.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Johor", "Kedah", "Kelantan", "Kuala Lumpur", "Labuan", "Malacca", "Negeri Sembilan", "Pahang", "Perak", "Perlis", "Putrajaya", "Sabah", "Sarawak", "Selangor", "Sembilan", "Terengganu" }));
        changeProfilePanel.add(stateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 162, -1));

        genderButtonGroup.add(femaleRadioButton);
        femaleRadioButton.setText("Female");
        changeProfilePanel.add(femaleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        genderButtonGroup.add(maleRadioButton);
        maleRadioButton.setText("Male");
        changeProfilePanel.add(maleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel44.setText("IC/Passport Number");
        changeProfilePanel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 210, 20));

        userIDText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        userIDText.setEnabled(false);
        changeProfilePanel.add(userIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 162, -1));

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(changeProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
            .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(changePassPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                    .addGap(0, 97, Short.MAX_VALUE)
                    .addComponent(changePassPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        mainPanels.add(profilePanel, "profilePane");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sideMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homePanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelButtonMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanels.getLayout();
        card.show(mainPanels, "homePane");
        homePanelButton.setBackground(Color.white);
        appointmentPanelButton.setBackground(new Color(41,48,57));
        statusPanelButton.setBackground(new Color(41,48,57));
        profilePanelButton.setBackground(new Color(41,48,57));
        homeButtonLabel.setForeground(Color.black);
        appointmentButtonLabel.setForeground(Color.white);
        statusButtonLabel.setForeground(Color.white);
        profileButtonLabel.setForeground(Color.white);
    }//GEN-LAST:event_homePanelButtonMouseClicked

    private void appointmentPanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentPanelButtonMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanels.getLayout();
        card.show(mainPanels, "appointmentPane");
        appointmentPanelButton.setBackground(Color.white);
        homePanelButton.setBackground(new Color(41,48,57));
        statusPanelButton.setBackground(new Color(41,48,57));
        profilePanelButton.setBackground(new Color(41,48,57));
        homeButtonLabel.setForeground(Color.white);
        appointmentButtonLabel.setForeground(Color.black);
        statusButtonLabel.setForeground(Color.white);
        profileButtonLabel.setForeground(Color.white);
        Appointment appointment = new Appointment().getAppointmentDetails(userID);
        try {
            ucDateText.setText(appointment.getDate());
            ucTimeText.setText(appointment.getTime().toString());
            ucLocationText.setText(String.valueOf(appointment.getCentre()));
            ucVaccineText.setText(String.valueOf(appointment.getVaccine()));
        } 
        catch (Exception e)
        {
            
        }
    }//GEN-LAST:event_appointmentPanelButtonMouseClicked

    private void statusPanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusPanelButtonMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanels.getLayout();
        card.show(mainPanels, "statusPane");
        statusPanelButton.setBackground(Color.white);
        homePanelButton.setBackground(new Color(41,48,57));
        appointmentPanelButton.setBackground(new Color(41,48,57));
        profilePanelButton.setBackground(new Color(41,48,57));
        homeButtonLabel.setForeground(Color.white);
        appointmentButtonLabel.setForeground(Color.white);
        statusButtonLabel.setForeground(Color.black);
        profileButtonLabel.setForeground(Color.white);
    }//GEN-LAST:event_statusPanelButtonMouseClicked

    private void profilePanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelButtonMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanels.getLayout();
        card.show(mainPanels, "profilePane");
        profilePanelButton.setBackground(Color.white);
        homePanelButton.setBackground(new Color(41,48,57));
        statusPanelButton.setBackground(new Color(41,48,57));
        appointmentPanelButton.setBackground(new Color(41,48,57));
        homeButtonLabel.setForeground(Color.white);
        appointmentButtonLabel.setForeground(Color.white);
        statusButtonLabel.setForeground(Color.white);
        profileButtonLabel.setForeground(Color.black);
        
        changePassPanel.setVisible(false);
    }//GEN-LAST:event_profilePanelButtonMouseClicked

    private void cancelChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelChangeButtonActionPerformed
        // TODO add your handling code here:
        changePassPanel.setVisible(false);
        changeProfilePanel.setVisible(true);
    }//GEN-LAST:event_cancelChangeButtonActionPerformed

    private void changePassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassButtonActionPerformed
        // TODO add your handling code here:
        changePassPanel.setVisible(true);
        changeProfilePanel.setVisible(false);
    }//GEN-LAST:event_changePassButtonActionPerformed

    private void saveProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProfileButtonActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat dcn = new SimpleDateFormat("dd-MM-yyyy");
            People existingPpl = new People().getPeopleDetails(userID);
    //        People newPeople = new People();
    //        newPeople.setUsername(userIDText.getText());
    //        newPeople.setName(nameText.getText());
    //        newPeople.setPhoneNum(Integer.parseInt(phoneNumText.getText()));
    //        newPeople.setDate(dcn.format(dobDateChooser.getDate()));
    //        newPeople.setState(String.valueOf(stateComboBox.getSelectedItem()));
    //        newPeople.setCitizenship(citizenshipText.getText());
    //        newPeople.setGender(getSelectedButton());
    //        newPeople.modifyProfile(newPeople);
            existingPpl.setUsername(userIDText.getText());
            existingPpl.setName(nameText.getText());
            if (new Login().isValidPhoneNum(phoneNumText.getText()))
                existingPpl.setPhoneNum(phoneNumText.getText());
            else { throw new PhoneNumberFormatException("Phone Number Format Invalid!"); }
            existingPpl.setDate(dcn.format(dobDateChooser.getDate()));
            existingPpl.setState(String.valueOf(stateComboBox.getSelectedItem()));
            existingPpl.setCitizenship(citizenshipText.getText());
            existingPpl.setGender(getSelectedButton());
            existingPpl.modifyProfile(existingPpl);
        } catch (PhoneNumberFormatException e){
            JOptionPane.showMessageDialog(null, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_saveProfileButtonActionPerformed

    private void confChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confChangeButtonActionPerformed
        // TODO add your handling code here:
        People existingPpl = new People().getPeopleDetails(userID);
        if (existingPpl.getPassword().equals(currentPassText.getText()))
        {
            existingPpl.setPassword(newPassText.getText());
            existingPpl.changePassword(existingPpl);
        }
    }//GEN-LAST:event_confChangeButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void searchStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStatusButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dcn = new SimpleDateFormat("dd-MM-yyyy");
        try{
            String dateSelected = dcn.format(statusDateChooser.getDate());
            jLabel47.setText("Vaccination Status on " + dcn.format(statusDateChooser.getDate()));
            DefaultTableModel table = (DefaultTableModel) statusTable.getModel();
            table.setRowCount(0);
            int count=0;
            Centre centreDetails = new Centre();
            if (!centreSearchCombo.getSelectedItem().equals("None"))
            {
                centreDetails = centreDetails
                        .searchCentre(String.valueOf(centreSearchCombo
                                .getSelectedItem()));
            }

            if (!vaccineSearchCombo.getSelectedItem().equals("None") && 
                    !centreSearchCombo.getSelectedItem().equals("None"))
            {
                for (Vaccine vaccine:centreDetails.getVaccine())
                {
                    if (vaccine.getVaccineName()
                            .equals(String.valueOf(vaccineSearchCombo
                            .getSelectedItem())))
                    {
                        count++;
                        String[] row = {centreDetails.getCentreName(), 
                            centreDetails.getCentreLocation(), 
                            String.valueOf(vaccineSearchCombo
                                .getSelectedItem()), 
                            Integer.toString(getRemainingVaccine(
                                    vaccine.getVaccineName(), 
                                    centreDetails.getCentreName(),dateSelected)) };
                        table.addRow(row);
                    }
                }
            }
            else if (!vaccineSearchCombo.getSelectedItem().equals("None") && 
                    centreSearchCombo.getSelectedItem().equals("None"))
            {
                HashMap<String, String> allCentre = new Centre().getAllCentre();
                for (String eachCentreName:allCentre.keySet())
                {
                    if (new Centre().getCentreVaccines(eachCentreName)
                            .contains(String.valueOf(vaccineSearchCombo
                            .getSelectedItem())))
                    {
                        count++;
                        String[] row = {eachCentreName, 
                            allCentre.get(allCentre), 
                            String.valueOf(vaccineSearchCombo.getSelectedItem()), 
                            Integer.toString(getRemainingVaccine(
                                    (String) vaccineSearchCombo.getSelectedItem(), 
                                    eachCentreName, dateSelected))};
                        table.addRow(row);
                    }
                }
            }
            else if (vaccineSearchCombo.getSelectedItem().equals("None") && 
                    !centreSearchCombo.getSelectedItem().equals("None"))
            {
                for (Vaccine vaccine:centreDetails.getVaccine())
                {
                    count++;
                    String[] row = {centreDetails.getCentreName(), 
                        centreDetails.getCentreLocation(), 
                        vaccine.getVaccineName(), 
                        Integer.toString(getRemainingVaccine(
                                vaccine.getVaccineName(), 
                                centreDetails.getCentreName(), dateSelected))};
                    table.addRow(row);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, 
                        "No options are selected to search!", "Error", 
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch(NullPointerException ex) {
            JOptionPane.showMessageDialog(null, 
                        "Please select a date to search!", "Error", 
                        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchStatusButtonActionPerformed

    private void centreComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centreComboActionPerformed
        // TODO add your handling code here:
        final DefaultComboBoxModel vaccineModel = new DefaultComboBoxModel(
                (new Centre().getCentreVaccines((String) centreCombo
                        .getSelectedItem()).toArray()));
        vaccineCombo.setModel(vaccineModel);
    }//GEN-LAST:event_centreComboActionPerformed

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dcn = new SimpleDateFormat("dd-MM-yyyy");
        Appointment newAppointment = new Appointment();
        newAppointment.setDate(dcn.format(apDateChooser.getDate()));
        newAppointment.setExpDate(dcn.format(apDateChooser.getDate()));
        String time = apHourSlider.getValue() + ":" + apMinuteSlider.getValue();
        newAppointment.setDoseNum(newAppointment.checkDoseNum(userID));
        newAppointment.setTime(LocalTime.parse(time));
        newAppointment.setPeople(new People().getPeopleDetails(userID));
        newAppointment.setCentre(new Centre().searchCentre((String) centreCombo.getSelectedItem()));
        newAppointment.setVaccine(new Vaccine().searchVaccine((String) vaccineCombo.getSelectedItem()));
        newAppointment.regAppointment(newAppointment);  
    }//GEN-LAST:event_regButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
            ((JTextField)apDateChooser.getDateEditor().getUiComponent()).setText("Appointment Date");
            centreCombo.setEditable(true);
            centreCombo.setSelectedItem("Select a Centre");
            vaccineCombo.setEditable(true);
            vaccineCombo.setSelectedItem("Please Select a Centre First");
            apHourSlider.setValue(((SpinnerNumberModel) apHourSlider.getModel()).getMinimum());
            apMinuteSlider.setValue(((SpinnerNumberModel) apMinuteSlider.getModel()).getMinimum());
    }//GEN-LAST:event_clearButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        boolean idFound = new Appointment().deleteAppointment(userID);
        if (idFound == true)
            {
                JOptionPane.showMessageDialog(null, "Appointment Cancel Successfully.");
            }
        else
            {
                JOptionPane.showMessageDialog(null, "Appointment Not Found.", "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        }
        catch (Exception e){
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeopleGUI().setVisible(true);
            }
        });
    }
    
    private void showProfileDetails()
    {
        try {
            People ppl = new People().getPeopleDetails(userID);
            
            Date dob = new SimpleDateFormat("dd-MM-yyyy").parse(ppl.getDate());
            
            userIDText.setText(userID);
            nameText.setText(ppl.getName());
            phoneNumText.setText(ppl.getPhoneNum());
            dobDateChooser.setDate(dob);
            stateComboBox.setSelectedItem(ppl.getState());
            citizenshipText.setText(ppl.getCitizenship());
            if (ppl.getGender().equals("Male")) { maleRadioButton.setSelected(true); }
            else { femaleRadioButton.setSelected(true); }
        } catch (ParseException ex) {
            Logger.getLogger(PeopleGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private String getSelectedButton()
    {  
        for (Enumeration<AbstractButton> buttons = genderButtonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                    return button.getText();
            }
        }
        return null;
    }   
    
    private int getRemainingVaccine(String vacName, String centreName, String apDate)
    {
        int count=0;
        ArrayList<Appointment> apList = new Appointment().getAppointments(vacName, centreName);
        if (!apList.isEmpty())
        {
            for (Appointment eachAP:apList)
            {
                if (eachAP.getDate().equals(apDate))
                {
                    count++;
                }
            }
            int vacQuantity = 0;
            for (Vaccine eachVac:new Centre().searchCentre(centreName).getVaccine())
            {
                if (eachVac.getVaccineName().equals(vacName))
                {
                    vacQuantity = eachVac.getVaccineQuantity();
                }
            }
            int remainingVac = vacQuantity - count;
            return remainingVac;
        }
        else { return 500; }
    }
    
    private void updateDashboard()
    {
        People thisPeople = new People().getPeopleDetails(userID);
        jLabel2.setText("Welcome, " + thisPeople.getName());
        LocalDate currentDate = LocalDate.now();
        jLabel3.setText("You have " + Integer.toString(
                new Appointment().getFutureAppointments(userID, currentDate)
                        .size()) + " upcoming vaccination appointment");
        if (!thisPeople.getDose1().getAppointmentID().equals("none"))
        {
            jLabel39.setText("Date:\n" + thisPeople.getDose1().getDate());
            jLabel40.setText("Vaccine Name:\n" + thisPeople.getDose1().getVaccine().getVaccineName());
            jLabel42.setText("Location:\n" + thisPeople.getDose1().getCentre().getCentreName());
            
            if(!thisPeople.getDose2().getAppointmentID().equals("none"))
            {
                jLabel41.setText("Date:\n" + thisPeople.getDose2().getDate());
                jLabel43.setText("Vaccine Name:\n" + thisPeople.getDose2().getVaccine().getVaccineName());
                jLabel49.setText("Location:\n" + thisPeople.getDose2().getCentre().getCentreName());
            }
            else {
                jPanel6.setVisible(false);
            }
        }
        else {
            jPanel5.setVisible(false);
            jPanel6.setVisible(false);
            jLabel50.setText("Unvaccinated");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser apDateChooser;
    private javax.swing.JSpinner apHourSlider;
    private javax.swing.JSpinner apMinuteSlider;
    private javax.swing.JLabel appointmentButtonLabel;
    private javax.swing.JPanel appointmentPanel;
    private javax.swing.JPanel appointmentPanelButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelChangeButton;
    private javax.swing.JComboBox<String> centreCombo;
    private javax.swing.JComboBox<String> centreSearchCombo;
    private javax.swing.JButton changePassButton;
    private javax.swing.JPanel changePassPanel;
    private javax.swing.JPanel changeProfilePanel;
    private javax.swing.JTextField citizenshipText;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton confChangeButton;
    private javax.swing.JTextField currentPassText;
    private com.toedter.calendar.JDateChooser dobDateChooser;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel homeButtonLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel homePanelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel mainPanels;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField newPassText;
    private javax.swing.JTextField phoneNumText;
    private javax.swing.JLabel profileButtonLabel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JPanel profilePanelButton;
    private javax.swing.JButton regButton;
    private javax.swing.JButton saveProfileButton;
    private javax.swing.JButton searchStatusButton;
    private javax.swing.JPanel sideMenuPanel;
    private javax.swing.JComboBox<String> stateComboBox;
    private javax.swing.JLabel statusButtonLabel;
    private com.toedter.calendar.JDateChooser statusDateChooser;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JPanel statusPanelButton;
    private javax.swing.JTable statusTable;
    private javax.swing.JTextField ucDateText;
    private javax.swing.JTextField ucLocationText;
    private javax.swing.JTextField ucTimeText;
    private javax.swing.JTextField ucVaccineText;
    private javax.swing.JTextField userIDText;
    private javax.swing.JComboBox<String> vaccineCombo;
    private javax.swing.JComboBox<String> vaccineSearchCombo;
    private javax.swing.JLabel virusImage;
    // End of variables declaration//GEN-END:variables
}
