/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registration.system;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.toedter.calendar.JDateChooser;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author nigel
 */
public class PersonnelGUI extends javax.swing.JFrame {
    private final String dataUser = "dataUser.txt";
    /**
     * Creates new form Personnel
     */
    public PersonnelGUI() {
        initComponents();
        setPreferredSize(new Dimension(1080, 670));
        pack();
        updatePeopleTable();
        updateAppointmentTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        sidePanels = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        appointmentPanelButton = new javax.swing.JPanel();
        appointmentButtonLabel = new javax.swing.JLabel();
        vaccinePanelButton = new javax.swing.JPanel();
        vaccineButtonLabel = new javax.swing.JLabel();
        homePanelButton = new javax.swing.JPanel();
        homeButtonLabel = new javax.swing.JLabel();
        peoplePanelButton = new javax.swing.JPanel();
        peopleButtonLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        logOutButton = new javax.swing.JButton();
        mainPanels = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        appointmentPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        centreAPCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        apIDSearchText = new javax.swing.JTextField();
        searchAPButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        dateAPChooser = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        apHourSlider = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        apMinuteSlider = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        vaccineAPCombo = new javax.swing.JComboBox<>();
        adAPButton = new javax.swing.JButton();
        clearAPButton = new javax.swing.JButton();
        saveAPButton = new javax.swing.JButton();
        deleteAPButton = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        apIDText = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        peopleAPText = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        appointmentTable = new javax.swing.JTable();
        peoplePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        peopleTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        userIDText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        searchPeopleButton = new javax.swing.JButton();
        peopleNameText = new javax.swing.JTextField();
        usernamePeopleText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        passPeopleText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        phonePeopleText = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        dobPeopleChooser = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        citizenPeopleText = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        malePeopleButton = new javax.swing.JRadioButton();
        femalePeopleButton = new javax.swing.JRadioButton();
        addPeopleButton = new javax.swing.JButton();
        deletePeopleButton = new javax.swing.JButton();
        savePeopleButton = new javax.swing.JButton();
        clearPeopleButton = new javax.swing.JButton();
        stateComboBox = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        statusPeopleText = new javax.swing.JTextField();
        vaccinePanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personnel Dashboard");
        setMinimumSize(new java.awt.Dimension(1073, 640));
        setResizable(false);

        sidePanels.setBackground(new java.awt.Color(41, 48, 57));
        sidePanels.setPreferredSize(new java.awt.Dimension(268, 640));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        appointmentPanelButton.setBackground(new java.awt.Color(41, 48, 57));
        appointmentPanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentPanelButtonMouseClicked(evt);
            }
        });

        appointmentButtonLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        appointmentButtonLabel.setForeground(new java.awt.Color(255, 255, 255));
        appointmentButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appointmentButtonLabel.setText("Appointments");

        javax.swing.GroupLayout appointmentPanelButtonLayout = new javax.swing.GroupLayout(appointmentPanelButton);
        appointmentPanelButton.setLayout(appointmentPanelButtonLayout);
        appointmentPanelButtonLayout.setHorizontalGroup(
            appointmentPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appointmentButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        appointmentPanelButtonLayout.setVerticalGroup(
            appointmentPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appointmentButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        vaccinePanelButton.setBackground(new java.awt.Color(41, 48, 57));
        vaccinePanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vaccinePanelButtonMouseClicked(evt);
            }
        });

        vaccineButtonLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        vaccineButtonLabel.setForeground(new java.awt.Color(255, 255, 255));
        vaccineButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vaccineButtonLabel.setText("Vaccine");

        javax.swing.GroupLayout vaccinePanelButtonLayout = new javax.swing.GroupLayout(vaccinePanelButton);
        vaccinePanelButton.setLayout(vaccinePanelButtonLayout);
        vaccinePanelButtonLayout.setHorizontalGroup(
            vaccinePanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vaccineButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vaccinePanelButtonLayout.setVerticalGroup(
            vaccinePanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vaccineButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        homePanelButton.setBackground(new java.awt.Color(255, 255, 255));
        homePanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePanelButtonMouseClicked(evt);
            }
        });

        homeButtonLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        homeButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeButtonLabel.setText("Home");

        javax.swing.GroupLayout homePanelButtonLayout = new javax.swing.GroupLayout(homePanelButton);
        homePanelButton.setLayout(homePanelButtonLayout);
        homePanelButtonLayout.setHorizontalGroup(
            homePanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homePanelButtonLayout.setVerticalGroup(
            homePanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        peoplePanelButton.setBackground(new java.awt.Color(41, 48, 57));
        peoplePanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peoplePanelButtonMouseClicked(evt);
            }
        });

        peopleButtonLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        peopleButtonLabel.setForeground(new java.awt.Color(255, 255, 255));
        peopleButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        peopleButtonLabel.setText("People");

        javax.swing.GroupLayout peoplePanelButtonLayout = new javax.swing.GroupLayout(peoplePanelButton);
        peoplePanelButton.setLayout(peoplePanelButtonLayout);
        peoplePanelButtonLayout.setHorizontalGroup(
            peoplePanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(peopleButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        peoplePanelButtonLayout.setVerticalGroup(
            peoplePanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(peopleButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        logOutButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_Logout_26px.png"))); // NOI18N
        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelsLayout = new javax.swing.GroupLayout(sidePanels);
        sidePanels.setLayout(sidePanelsLayout);
        sidePanelsLayout.setHorizontalGroup(
            sidePanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(appointmentPanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(peoplePanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(vaccinePanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(sidePanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        sidePanelsLayout.setVerticalGroup(
            sidePanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelsLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(homePanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appointmentPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peoplePanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vaccinePanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        mainPanels.setLayout(new java.awt.CardLayout());

        homePanel.setMinimumSize(new java.awt.Dimension(771, 640));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setText("Dashboard");
        homePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Your account overview");
        homePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 60, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("Welcome, Powell");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("There are 100 users currently in the system");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        homePanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 470, 90));

        mainPanels.add(homePanel, "homePanel");

        appointmentPanel.setMinimumSize(new java.awt.Dimension(771, 640));
        appointmentPanel.setName(""); // NOI18N
        appointmentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("Appointments");
        appointmentPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("Manage all appointments");
        appointmentPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 60, -1, -1));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N
        appointmentPanel.add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 540, 420));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        centreAPCombo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        centreAPCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "World Trade Centre KL", "Wisma Belia", "Stadium Tun Abdul Razak", "Pusat Sains dan Kreativiti", "Kuala Lumpur Convention Centre", "Ideal Convention Centre", "Borneo Convention Centre Kuching", "Axiata Arena Bukit Jalil" }));
        centreAPCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centreAPComboActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Add New Appointment");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Enter Appointment ID to Search: ");

        apIDSearchText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        searchAPButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_search_26px_2.png"))); // NOI18N
        searchAPButton.setText("Search");
        searchAPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAPButtonActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setText("Vaccination Centre");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel27.setText("Date");

        dateAPChooser.setDateFormatString("dd-MM-yyyy\n");
        dateAPChooser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel28.setText("Time");

        apHourSlider.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        apHourSlider.setModel(new javax.swing.SpinnerNumberModel(1, 1, 24, 1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel29.setText(":");

        apMinuteSlider.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        apMinuteSlider.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 30));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel30.setText("Vaccination Type");

        vaccineAPCombo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        vaccineAPCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pfizer-BioNtech", "AstraZeneca", "Janssen/Ad26.COV 2.S", "Sputnik V", "Sinovac-CoronaVac", "Cansino Biologics" }));
        vaccineAPCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineAPComboActionPerformed(evt);
            }
        });

        adAPButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        adAPButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_add_26px_1.png"))); // NOI18N
        adAPButton.setText("Add");
        adAPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adAPButtonActionPerformed(evt);
            }
        });

        clearAPButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        clearAPButton.setText("Clear");
        clearAPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAPButtonActionPerformed(evt);
            }
        });

        saveAPButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        saveAPButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_save_26px.png"))); // NOI18N
        saveAPButton.setText("Save");
        saveAPButton.setEnabled(false);
        saveAPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAPButtonActionPerformed(evt);
            }
        });

        deleteAPButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        deleteAPButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_Delete_26px.png"))); // NOI18N
        deleteAPButton.setText("Delete");
        deleteAPButton.setEnabled(false);
        deleteAPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAPButtonActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel31.setText("Appointment ID");

        apIDText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        apIDText.setEnabled(false);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel32.setText("IC/Passport Number");

        peopleAPText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(apIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(peopleAPText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel27)
                            .addGap(170, 170, 170))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel28)
                            .addGap(161, 161, 161))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(dateAPChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(apHourSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apMinuteSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(centreAPCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaccineAPCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(saveAPButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteAPButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearAPButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adAPButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apIDSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchAPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(adAPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(clearAPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(saveAPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(deleteAPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel31))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateAPChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(apIDText))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel30))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(apHourSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29)
                                            .addComponent(apMinuteSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vaccineAPCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(peopleAPText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(centreAPCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(apIDSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchAPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        appointmentPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 751, 340));

        appointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "AppointmentID", "Date", "Time", "Centre", "User ID", "Expiry Date", "Vaccine Type", "Dose Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        appointmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(appointmentTable);

        appointmentPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 750, 170));

        mainPanels.add(appointmentPanel, "appointmentPanel");

        peoplePanel.setMinimumSize(new java.awt.Dimension(771, 640));
        peoplePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setText("People");
        peoplePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setText("Manage all users in the system");
        peoplePanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 60, -1, -1));

        peopleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PeopleID", "Name", "UserID", "UserPassword", "Phone Number", "Date of Birth", "Gender", "State", "Citizenship", "Status", "Dose 1", "Dose 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        peopleTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        peopleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peopleTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(peopleTable);

        peoplePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 750, 170));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Add New People");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Enter IC Number to Search: ");

        userIDText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setText("Name");

        searchPeopleButton.setText("Search");
        searchPeopleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPeopleButtonActionPerformed(evt);
            }
        });

        peopleNameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        usernamePeopleText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setText("Password");

        passPeopleText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setText("Phone Number");

        phonePeopleText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setText("Date of Birth");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setText("Status");

        dobPeopleChooser.setDateFormatString("dd-MM-yyyy");
        dobPeopleChooser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setText("Citizenship");

        citizenPeopleText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel25.setText("Gender");

        genderButtonGroup.add(malePeopleButton);
        malePeopleButton.setText("Male");

        genderButtonGroup.add(femalePeopleButton);
        femalePeopleButton.setText("Female");

        addPeopleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_registration_26px.png"))); // NOI18N
        addPeopleButton.setText("Add");
        addPeopleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPeopleButtonActionPerformed(evt);
            }
        });

        deletePeopleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_Delete_26px.png"))); // NOI18N
        deletePeopleButton.setText("Delete");
        deletePeopleButton.setEnabled(false);
        deletePeopleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePeopleButtonActionPerformed(evt);
            }
        });

        savePeopleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_save_26px.png"))); // NOI18N
        savePeopleButton.setText("Save");
        savePeopleButton.setEnabled(false);
        savePeopleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePeopleButtonActionPerformed(evt);
            }
        });

        clearPeopleButton.setText("Clear");
        clearPeopleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPeopleButtonActionPerformed(evt);
            }
        });

        stateComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Johor", "Kedah", "Kelantan", "Kuala Lumpur", "Labuan", "Malacca", "Negeri Sembilan", "Pahang", "Perak", "Perlis", "Putrajaya", "Sabah", "Sarawak", "Selangor", "Sembilan", "Terengganu" }));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel24.setText("IC/Passport Number");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel26.setText("State");

        statusPeopleText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statusPeopleText.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchPeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(peopleNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernamePeopleText, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passPeopleText, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dobPeopleChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                        .addComponent(phonePeopleText)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusPeopleText, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(malePeopleButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(femalePeopleButton))
                                        .addComponent(citizenPeopleText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(savePeopleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addPeopleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearPeopleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletePeopleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peopleNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel20)
                            .addComponent(jLabel25)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phonePeopleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(citizenPeopleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addPeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(savePeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernamePeopleText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobPeopleChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(malePeopleButton)
                            .addComponent(femalePeopleButton))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel26)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(clearPeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(passPeopleText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusPeopleText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(deletePeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(userIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        peoplePanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 751, 340));

        mainPanels.add(peoplePanel, "peoplePanel");

        vaccinePanel.setMinimumSize(new java.awt.Dimension(771, 640));
        vaccinePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setText("Vaccine");
        vaccinePanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel14.setText("Manage vaccines in every vaccination centre");
        vaccinePanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 60, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N
        vaccinePanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 540, 420));

        mainPanels.add(vaccinePanel, "vaccinePanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanels, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanels, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addComponent(sidePanels, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homePanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelButtonMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanels.getLayout();
        card.show(mainPanels, "homePanel");
        homePanelButton.setBackground(Color.white);
        appointmentPanelButton.setBackground(new Color(41,48,57));
        peoplePanelButton.setBackground(new Color(41,48,57));
        vaccinePanelButton.setBackground(new Color(41,48,57));
        homeButtonLabel.setForeground(Color.black);
        appointmentButtonLabel.setForeground(Color.white);
        peopleButtonLabel.setForeground(Color.white);
        vaccineButtonLabel.setForeground(Color.white);
    }//GEN-LAST:event_homePanelButtonMouseClicked

    private void appointmentPanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentPanelButtonMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanels.getLayout();
        card.show(mainPanels, "appointmentPanel");
        homePanelButton.setBackground(new Color(41,48,57));
        appointmentPanelButton.setBackground(Color.white);
        peoplePanelButton.setBackground(new Color(41,48,57));
        vaccinePanelButton.setBackground(new Color(41,48,57));
        homeButtonLabel.setForeground(Color.white);
        appointmentButtonLabel.setForeground(Color.black);
        peopleButtonLabel.setForeground(Color.white);
        vaccineButtonLabel.setForeground(Color.white);
    }//GEN-LAST:event_appointmentPanelButtonMouseClicked

    private void peoplePanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peoplePanelButtonMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanels.getLayout();
        card.show(mainPanels, "peoplePanel");
        homePanelButton.setBackground(new Color(41,48,57));
        appointmentPanelButton.setBackground(new Color(41,48,57));
        peoplePanelButton.setBackground(Color.white);
        vaccinePanelButton.setBackground(new Color(41,48,57));
        homeButtonLabel.setForeground(Color.white);
        appointmentButtonLabel.setForeground(Color.white);
        peopleButtonLabel.setForeground(Color.black);
        vaccineButtonLabel.setForeground(Color.white);
    }//GEN-LAST:event_peoplePanelButtonMouseClicked

    private void vaccinePanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaccinePanelButtonMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanels.getLayout();
        card.show(mainPanels, "vaccinePanel");
        homePanelButton.setBackground(new Color(41,48,57));
        appointmentPanelButton.setBackground(new Color(41,48,57));
        peoplePanelButton.setBackground(new Color(41,48,57));
        vaccinePanelButton.setBackground(Color.white);
        homeButtonLabel.setForeground(Color.white);
        appointmentButtonLabel.setForeground(Color.white);
        peopleButtonLabel.setForeground(Color.white);
        vaccineButtonLabel.setForeground(Color.black);
    }//GEN-LAST:event_vaccinePanelButtonMouseClicked

    private void clearPeopleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPeopleButtonActionPerformed
        // TODO add your handling code here:
//        peopleNameText.setText("");
//        usernamePeopleText.setText("");
//        passPeopleText.setText("");
//        phonePeopleText.setText("");
//        ((JTextField)dobPeopleChooser.getDateEditor().getUiComponent()).setText("Date of Birth");
//        stateComboBox.setEditable(true);
//        stateComboBox.setSelectedItem("State");
//        citizenPeopleText.setText("");
//        malePeopleButton.setSelected(false);
//        femalePeopleButton.setSelected(false);
//        statusPeopleText.setText("");
        clearComponents(jPanel2);
        usernamePeopleText.setEnabled(true);
        deletePeopleButton.setEnabled(false);
        addPeopleButton.setEnabled(true);
        savePeopleButton.setEnabled(false);
    }//GEN-LAST:event_clearPeopleButtonActionPerformed

    private void peopleTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peopleTableMouseClicked
        // TODO add your handling code here:
        int row = peopleTable.getSelectedRow();
        String userID = String.valueOf(peopleTable.getValueAt(row, 2));
        displayPeopleDetails(new People().getPeopleDetails(userID));
        usernamePeopleText.setEnabled(false);
        deletePeopleButton.setEnabled(true);
        addPeopleButton.setEnabled(false);
        savePeopleButton.setEnabled(true);
    }//GEN-LAST:event_peopleTableMouseClicked

    private void searchPeopleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPeopleButtonActionPerformed
        // TODO add your handling code here:
        People ppl = new People().getPeopleDetails(userIDText.getText());
        if (ppl != null)
        {
            displayPeopleDetails(ppl);
            usernamePeopleText.setEnabled(false);
            deletePeopleButton.setEnabled(true);
            addPeopleButton.setEnabled(false);
            savePeopleButton.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Customer with PeopleID" + 
                    userIDText.getText() + " not found!", "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchPeopleButtonActionPerformed

    private void addPeopleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPeopleButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dcn = new SimpleDateFormat("dd-MM-yyyy");
        try {
            if(new Login().isValidUserID(usernamePeopleText.getText()))
            {
                if (new Login().isValidPassword(passPeopleText.getText()))
                {
                    Appointment emptyAppointment = new Appointment();
                    emptyAppointment.setAppointmentID("null");
                    People newPeople = new People();
                    newPeople.setName(peopleNameText.getText());
                    newPeople.setPhoneNum(phonePeopleText.getText());
                    newPeople.setUsername(usernamePeopleText.getText());
                    newPeople.setPassword(passPeopleText.getText());
                    newPeople.setDate(dcn.format(dobPeopleChooser.getDate()));
                    newPeople.setState(String.valueOf(stateComboBox.getSelectedItem()));
                    newPeople.setCitizenship(citizenPeopleText.getText());
                    newPeople.setGender(getSelectedButton());
                    newPeople.setUserType("People");
                    newPeople.setStatus("Unvaccinated");
                    newPeople.setDose1(emptyAppointment);
                    newPeople.setDose2(emptyAppointment);
                    newPeople.registerProfile(newPeople);
                    JOptionPane.showMessageDialog(null, "Account registered "
                    + "successfully.");
                    updatePeopleTable();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "IC/Passport Number Format is Invalid!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        clearComponents(jPanel2);
        usernamePeopleText.setEnabled(true);
        deletePeopleButton.setEnabled(false);
        addPeopleButton.setEnabled(true);
        savePeopleButton.setEnabled(false);
    }//GEN-LAST:event_addPeopleButtonActionPerformed

    private void savePeopleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePeopleButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dcn = new SimpleDateFormat("dd-MM-yyyy");
        People existingPpl = new People().getPeopleDetails(usernamePeopleText.getText());
        existingPpl.setName(peopleNameText.getText());
        existingPpl.setPhoneNum(phonePeopleText.getText());
        existingPpl.setUsername(usernamePeopleText.getText());
        existingPpl.setPassword(passPeopleText.getText());
        existingPpl.setDate(dcn.format(dobPeopleChooser.getDate()));
        existingPpl.setState(String.valueOf(stateComboBox.getSelectedItem()));
        existingPpl.setCitizenship(citizenPeopleText.getText());
        existingPpl.setGender(getSelectedButton());
        existingPpl.modifyProfile(existingPpl);
        updatePeopleTable();
        clearComponents(jPanel2);
        usernamePeopleText.setEnabled(true);
        deletePeopleButton.setEnabled(false);
        addPeopleButton.setEnabled(true);
        savePeopleButton.setEnabled(false);
    }//GEN-LAST:event_savePeopleButtonActionPerformed

    private void deletePeopleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePeopleButtonActionPerformed
        // TODO add your handling code here:
        boolean idFound = new People().deletePeople(usernamePeopleText.getText());
        if (idFound == true)
            {
                JOptionPane.showMessageDialog(null, "People Deleted Successfully.");
                updatePeopleTable();
                clearComponents(jPanel2);
                usernamePeopleText.setEnabled(true);
                deletePeopleButton.setEnabled(false);
                addPeopleButton.setEnabled(true);
                savePeopleButton.setEnabled(false);
            }
        else
            {
                JOptionPane.showMessageDialog(null, "UserID Not Found. Profile Cannot be Deleted.", "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_deletePeopleButtonActionPerformed

    private void deleteAPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAPButtonActionPerformed
        // TODO add your handling code here:
        boolean idFound = new Appointment().deleteAppointment(apIDText.getText());
        if (idFound == true)
            {
                JOptionPane.showMessageDialog(null, "Appointment Deleted Successfully.");
                updateAppointmentTable();
                clearAppointment(jPanel1);
                peopleAPText.setEnabled(true);
                deleteAPButton.setEnabled(false);
                adAPButton.setEnabled(true);
                saveAPButton.setEnabled(false);
            }
        else
            {
                JOptionPane.showMessageDialog(null, "Appointment Not Found.", "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_deleteAPButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void adAPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adAPButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dcn = new SimpleDateFormat("dd-MM-yyyy");
        try {
            if (new People().checkUserID(peopleAPText.getText()) == true)
            {
                Appointment newAppointment = new Appointment();
                newAppointment.setDate(dcn.format(dateAPChooser.getDate()));
                newAppointment.setExpDate(dcn.format(dateAPChooser.getDate()));
                String time = apHourSlider.getValue() + ":" + apMinuteSlider.getValue();
                newAppointment.setDoseNum(newAppointment.checkDoseNum(peopleAPText.getText()));
                newAppointment.setTime(LocalTime.parse(time));
                newAppointment.setPeople(new People().getPeopleDetails(peopleAPText.getText()));
                newAppointment.setCentre(new Centre().searchCentre((String) centreAPCombo.getSelectedItem()));
                newAppointment.setVaccine(new Vaccine().searchVaccine((String) vaccineAPCombo.getSelectedItem()));
                newAppointment.regAppointment(newAppointment);  
                JOptionPane.showMessageDialog(null, "Appointment Added Successfully.");
                updateAppointmentTable();
                clearAppointment(jPanel1);
                peopleAPText.setEnabled(true);
                deleteAPButton.setEnabled(false);
                adAPButton.setEnabled(true);
                saveAPButton.setEnabled(false);
            } 
            else
            {
                JOptionPane.showMessageDialog(null, "IC/Passport Number Not Found.");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_adAPButtonActionPerformed

    private void vaccineAPComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineAPComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccineAPComboActionPerformed

    private void centreAPComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centreAPComboActionPerformed
        final DefaultComboBoxModel vaccineModel = new DefaultComboBoxModel(
                (new Centre().getCentreVaccines((String) centreAPCombo
                        .getSelectedItem()).toArray()));
        vaccineAPCombo.setModel(vaccineModel);        // TODO add your handling code here:
    }//GEN-LAST:event_centreAPComboActionPerformed

    private void clearAPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAPButtonActionPerformed
        // TODO add your handling code here:
        clearAppointment(jPanel1);
        peopleAPText.setEnabled(true);
        deleteAPButton.setEnabled(false);
        adAPButton.setEnabled(true);
        saveAPButton.setEnabled(false);
    }//GEN-LAST:event_clearAPButtonActionPerformed

    private void appointmentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentTableMouseClicked
        // TODO add your handling code here:
        int row = appointmentTable.getSelectedRow();
        String appointmentID = String.valueOf(appointmentTable.getValueAt(row, 0));
        displayAppointmentDetails(new Appointment().getAppointmentDetails(appointmentID));
        peopleAPText.setEnabled(false);
        deleteAPButton.setEnabled(true);
        adAPButton.setEnabled(false);
        saveAPButton.setEnabled(true);
    }//GEN-LAST:event_appointmentTableMouseClicked

    private void saveAPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAPButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dcn = new SimpleDateFormat("dd-MM-yyyy");
        Appointment savedAppointment = new Appointment();
        savedAppointment.setDate(dcn.format(dateAPChooser.getDate()));
        savedAppointment.setExpDate(dcn.format(dateAPChooser.getDate()));
        String time = apHourSlider.getValue() + ":" + apMinuteSlider.getValue();
        savedAppointment.getDoseNum();
        savedAppointment.setTime(LocalTime.parse(time));
        savedAppointment.setPeople(new People().getPeopleDetails(peopleAPText.getText()));
        savedAppointment.setCentre(new Centre().searchCentre((String) centreAPCombo.getSelectedItem()));
        savedAppointment.setVaccine(new Vaccine().searchVaccine((String) vaccineAPCombo.getSelectedItem()));
        savedAppointment.modifyAppointment(savedAppointment);
        updateAppointmentTable();
        clearAppointment(jPanel1);
        peopleAPText.setEnabled(true);
        deleteAPButton.setEnabled(false);
        adAPButton.setEnabled(true);
        saveAPButton.setEnabled(false);
    }//GEN-LAST:event_saveAPButtonActionPerformed

    private void searchAPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAPButtonActionPerformed
        // TODO add your handling code here:
        Appointment appointment = new Appointment().getAppointmentDetails(apIDSearchText.getText());
        if (appointment != null)
        {
            displayAppointmentDetails(appointment);
            peopleAPText.setEnabled(false);
            deleteAPButton.setEnabled(true);
            adAPButton.setEnabled(false);
            saveAPButton.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Appointment ID" + 
                    apIDSearchText.getText() + " not found!", "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchAPButtonActionPerformed
    
    static JComponent createVerticalSeparator() {
        JSeparator x = new JSeparator(SwingConstants.VERTICAL);
        x.setPreferredSize(new Dimension(3, 50));
        return x;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        }
        catch (Exception e){
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonnelGUI().setVisible(true);
            }
        });
    }
    
    private void updatePeopleTable()
    {
        DefaultTableModel table = (DefaultTableModel) peopleTable.getModel();
        table.setRowCount(0);
        int count=0;
        ObjectInputStream ois = null;
        try {
            ois = new ObjectInputStream(new FileInputStream(dataUser));
            Object obj = null;
            while ((obj = ois.readObject()) != null) {
                if (((User)obj).getUserType().equals("People"))
                {
                    count++;
                    String[] row = { ((People)obj).getPeopleID(), 
                        ((People)obj).getName(),
                        ((People)obj).getUsername(), ((People)obj).getPassword(), 
                        (((People)obj).getPhoneNum()), 
                        ((People)obj).getDate(), 
                        ((People)obj).getGender(), 
                        ((People)obj).getState(), ((People)obj).getCitizenship(), 
                        ((People)obj).getStatus(), ((People)obj).getDose1().getAppointmentID(), 
                        (((People)obj).getDose2()).getAppointmentID() };
                    table.addRow(row);
                }
            }
        } catch (EOFException ex) {} 
        catch (ClassNotFoundException ex) { ex.printStackTrace(); }
        catch (FileNotFoundException ex) { ex.printStackTrace(); }
        catch (IOException ex) { ex.printStackTrace(); }
        finally {
            try {
                if (ois != null) {
                    ois.close();
                }
            } catch (IOException ex) { ex.printStackTrace(); }
        }
    }
    
    private void displayPeopleDetails(People ppl)
    {
        try {
            Date dob = new SimpleDateFormat("dd-MM-yyyy").parse(ppl.getDate());
            peopleNameText.setText(ppl.getName());
            usernamePeopleText.setText(ppl.getUsername());
            passPeopleText.setText(ppl.getPassword());
            phonePeopleText.setText(ppl.getPhoneNum());
            dobPeopleChooser.setDate(dob);
            stateComboBox.setSelectedItem(ppl.getState());
            citizenPeopleText.setText(ppl.getCitizenship());
            if (ppl.getGender().equals("Male")) { malePeopleButton.setSelected(true); }
            else { femalePeopleButton.setSelected(true); }
            statusPeopleText.setText(ppl.getStatus());
        } catch (ParseException ex) {
            Logger.getLogger(PersonnelGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private String getSelectedButton()
    {  
        for (Enumeration<AbstractButton> buttons = genderButtonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                    return button.getText();
            }
        }
        return null;
    }
    
    private void clearComponents(javax.swing.JPanel panel)
    {
        for(Component control : panel.getComponents())
        {
            if(control instanceof JTextField)
            {
                JTextField ctrl = (JTextField) control;
                ctrl.setText("");
            }
            else if (control instanceof JComboBox)
            {
                JComboBox ctr = (JComboBox) control;
                ctr.setEditable(true);
                ctr.setSelectedItem("Select an Option");
            }
            else if (control instanceof JRadioButton)
            {
                JRadioButton rb = (JRadioButton) control;
                rb.setSelected(false);
            }
            else if (control instanceof JDateChooser)
            {
                JDateChooser dc = (JDateChooser) control;
                ((JTextField)dc.getDateEditor().getUiComponent()).setText("Date of Birth");
            }
        }
    }
    
    private void clearAppointment(javax.swing.JPanel panel)
    {
        for(Component control : panel.getComponents())
        {
            if(control instanceof JTextField)
            {
                JTextField ctrl = (JTextField) control;
                ctrl.setText("");
            }
            else if (control instanceof JComboBox)
            {
                JComboBox ctr = (JComboBox) control;
                ctr.setEditable(true);
                ctr.setSelectedItem("Select an Option");
            }          
            else if (control instanceof JDateChooser)
            {
                JDateChooser dc = (JDateChooser) control;
                ((JTextField)dc.getDateEditor().getUiComponent()).setText("Appointment Date");
            }
            else if (control instanceof JSpinner)
            {
                JSpinner spinner = (JSpinner) control;
                spinner.setValue(((SpinnerNumberModel) spinner.getModel()).getMinimum());
            }
        }
    }
    
    private void displayAppointmentDetails(Appointment appointment)
    {
        try {
            apIDText.setText(appointment.getAppointmentID());
            Date date = new SimpleDateFormat("dd-MM-yyyy").parse(appointment.getDate());
            dateAPChooser.setDate(date);
            peopleAPText.setText(appointment.getPeople().getUsername());
            centreAPCombo.setSelectedItem(appointment.getCentre());
            vaccineAPCombo.setSelectedItem(appointment.getVaccine());
            LocalTime time = appointment.getTime();
            int hour = time.getHour();
            int minute = time.getMinute();
            apHourSlider.setValue(hour);
            apMinuteSlider.setValue(minute);
        } 
        catch (ParseException ex) {
            Logger.getLogger(PersonnelGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void updateAppointmentTable()
    {
        DefaultTableModel table = (DefaultTableModel) appointmentTable.getModel();
        table.setRowCount(0);
        int count=0;
        ObjectInputStream ois = null;
        
        try {
            ois = new ObjectInputStream(new FileInputStream(new Appointment().getDataAppointment()));
            Object obj = null;
            while ((obj = ois.readObject()) != null) {
                count++;
                LocalTime time = ((Appointment)obj).getTime();
                String[] row = { ((Appointment)obj).getAppointmentID(), 
                    ((Appointment)obj).getDate(),
                    time.toString(),
                    ((Appointment)obj).getCentre().getCentreName(), 
                    ((Appointment)obj).getPeople().getUsername(), 
                    ((Appointment)obj).getExpDate(), 
                    ((Appointment)obj).getVaccine().getVaccineName(), 
                    Integer.toString(((Appointment)obj).getDoseNum())};
                table.addRow(row);

            }
        } catch (EOFException ex) {} 
        catch (ClassNotFoundException ex) { ex.printStackTrace(); }
        catch (FileNotFoundException ex) { ex.printStackTrace(); }
        catch (IOException ex) { ex.printStackTrace(); }
        finally {
            try {
                if (ois != null) {
                    ois.close();
                }
            } catch (IOException ex) { ex.printStackTrace(); }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adAPButton;
    private javax.swing.JButton addPeopleButton;
    private javax.swing.JSpinner apHourSlider;
    private javax.swing.JTextField apIDSearchText;
    private javax.swing.JTextField apIDText;
    private javax.swing.JSpinner apMinuteSlider;
    private javax.swing.JLabel appointmentButtonLabel;
    private javax.swing.JPanel appointmentPanel;
    private javax.swing.JPanel appointmentPanelButton;
    private javax.swing.JTable appointmentTable;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JComboBox<String> centreAPCombo;
    private javax.swing.JTextField citizenPeopleText;
    private javax.swing.JButton clearAPButton;
    private javax.swing.JButton clearPeopleButton;
    private com.toedter.calendar.JDateChooser dateAPChooser;
    private javax.swing.JButton deleteAPButton;
    private javax.swing.JButton deletePeopleButton;
    private com.toedter.calendar.JDateChooser dobPeopleChooser;
    private javax.swing.JRadioButton femalePeopleButton;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel homeButtonLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel homePanelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel mainPanels;
    private javax.swing.JRadioButton malePeopleButton;
    private javax.swing.JTextField passPeopleText;
    private javax.swing.JTextField peopleAPText;
    private javax.swing.JLabel peopleButtonLabel;
    private javax.swing.JTextField peopleNameText;
    private javax.swing.JPanel peoplePanel;
    private javax.swing.JPanel peoplePanelButton;
    private javax.swing.JTable peopleTable;
    private javax.swing.JTextField phonePeopleText;
    private javax.swing.JButton saveAPButton;
    private javax.swing.JButton savePeopleButton;
    private javax.swing.JButton searchAPButton;
    private javax.swing.JButton searchPeopleButton;
    private javax.swing.JPanel sidePanels;
    private javax.swing.JComboBox<String> stateComboBox;
    private javax.swing.JTextField statusPeopleText;
    private javax.swing.JTextField userIDText;
    private javax.swing.JTextField usernamePeopleText;
    private javax.swing.JComboBox<String> vaccineAPCombo;
    private javax.swing.JLabel vaccineButtonLabel;
    private javax.swing.JPanel vaccinePanel;
    private javax.swing.JPanel vaccinePanelButton;
    // End of variables declaration//GEN-END:variables
}
